package com.futureboundtech.dto;

import lombok.Data;
import lombok.experimental.Accessors;

/** The assistant turn produced by a chat request, plus flags the UI uses for badges. */
@Data
@Accessors(chain = true)
public class MentorReplyDto {

    /** Whether a real AI provider is configured (drives the "AI" vs "Offline guide" badge). */
    private boolean aiConfigured;

    /** Whether <em>this</em> answer was generated by the AI provider (vs the local fallback). */
    private boolean aiGenerated;

    /** The assistant message to render. */
    private MentorMessageDto reply;
}
